### ISSUE TITLE
_run_command shell redirection fails when not using SSH

### ISSUE THREAD

**Issue by robled** [jpwoodbu/ari-backup#9]
Output redirection seems to work fine when using SSH (consider the pre-hooks that are used to run pgdump or similar), but fails when run on localhost.  Here's a simple example that does nothing in my testing:

#!/usr/bin/env python

from ari_backup import LVMBackup

label = 'junk'

backup = LVMBackup(
    label=label,
    source_hostname='localhost',
    remove_older_than_timespec='1M'
)

backup._run_command('echo hi > /tmp/junk', host='localhost')

**Comment by rbarlow** [comment]
On 01/07/2015 09:51 PM, jpwoodbu wrote:
> David, can you confirm this actually works as expected when setting host
> != 'localhost'? Looking at the code (both old and new) and running some
> experiments, I'm wondering if what actually happens when host !=
> 'localhost' is that the file is dumped to the host running ari-backup
> rather than the remote host.

@jpwoodbu but how do i do localhost

**Comment by jpwoodbu** [comment]
Ping for @robled

**Comment by robled** [comment]
Re-testing with the pre-rewrite version of ari-backup.

Works as expected (file with contents is at /tmp/junk on remote host):

```
#!/usr/bin/env python

from ari_backup import LVMBackup

label = 'junk'

backup = LVMBackup(
    label=label,
    source_hostname='notlocalhost',
    remove_older_than_timespec='1M'
)

backup._run_command('echo hi > /tmp/junk', host='notlocalhost')
```

Does not work as expected (no file to be found on localhost at /tmp/junk):

```
#!/usr/bin/env python

from ari_backup import LVMBackup

label = 'junk'

backup = LVMBackup(
    label=label,
    source_hostname='localhost',
    remove_older_than_timespec='1M'
)

backup._run_command('echo hi > /tmp/junk', host='localhost')
```

**Comment by jpwoodbu** [comment]
@robled, thanks for running the test. I believe I see what's happening. Since SSH is not being called through a shell, the output redirection tokens are passed as arguments to SSH which then passes them  to the remote shell where they work as you would expect.

Given that remote command always get invoked with a shell and given that the end-user has complete control already on what Python is doing, I don't think there's any reason not to have all commands go through a shell. I'll look into making that change.
